export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE';
export const MODIFICATION_EMAIL = 'MODIFICATION_EMAIL';
export const MODIFICATION_PASSWORD = 'MODIFICATION_PASSWORD';
export const MODIFICATION_NAME = 'MODIFICATION_NAME';
export const MODIFICATION_REGISTER_USER_ERROR_MESSAGE = 'MODIFICATION_REGISTER_USER_ERROR_MESSAGE';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const LOGIN_IN_PROGRESS = 'LOGIN_IN_PROGRESS';
export const MODIFICATION_LOGIN_PROGRESS_START = 'MODIFICATION_LOGIN_PROGRESS_START';
export const MODIFICATION_LOGIN_PROGRESS_STOP = 'MODIFICATION_LOGIN_PROGRESS_STOP';
export const MODIFICATION_SIGNUP_PROGRESS = 'MODIFICATION_SIGNUP_PROGRESS';
export const SIGNUP_IN_PROGRESS = 'SIGNUP_IN_PROGRESS';


export const RESET_APP_REDUCER = 'RESET_APP_REDUCER';
export const MODIFICATION_CONTACT_EMAIL = 'MODIFICATION_CONTACT_EMAIL';
export const MODIFICATION_CONTACT_NAME = 'MODIFICATION_CONTACT_NAME';
export const ADD_CONTACT_ERR = 'ADD_CONTACT_ERR';
export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS';
export const LIST_USER_CONTACTS = 'LIST_USER_CONTACTS';
export const MODIFICATION_MESSAGE = 'MODIFICATION_MESSAGE';
export const LIST_USER_CHATTING = 'LIST_USER_CHATTING';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const RESET_AUTHENTICATION_REDUCER = 'RESET_AUTHENTICATION_REDUCER';
export const LIST_USER_CONVERSATION = 'LIST_USER_CONVERSATION';
export const LOGOUT_IN_PROGRESS = 'LOGOUT_IN_PROGRESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const IS_USER_LOGIN = 'IS_USER_LOGIN';

export const MODIFICATION_SIGNUP_EMAIL = 'MODIFICATION_SIGNUP_EMAIL';
export const MODIFICATION_SIGNUP_PASSWORD = 'MODIFICATION_SIGNUP_PASSWORD';

export const RESET_SIGNUP_FORM = 'RESET_SIGNUP_FORM';
export const RESET_LOGIN_FORM = 'RESET_LOGIN_FORM';
export const SEND_NOTIFICATION_SUCCESS = 'SEND_NOTIFICATION_SUCCESS';
export const LIST_NOTIFICATIONS = 'LIST_NOTIFICATIONS';
